// Generated by create-api-home — live runmoa Storefront config (pub key only, browser-safe).
window.RUNMOA = {
  "useApi": true,
  "siteHost": "privategolfperforman.runmoa.com",
  "storefrontKey": "moa_pub_xEB9RDkCaXi3q-Tr6p-uXMcmHsoh16IpoeeExnf0EXFM7aFhoxyGUYD6tyo69_3-",
  "limit": 48
};
